version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: aegir
    versions:
    - 30.3.0
    - 31.0.0
    - 31.0.1
    - 31.0.3
    - 31.0.4
    - 32.0.2
    - 32.1.0
    - 32.2.0
    - 33.0.0
    - 33.1.0
    - 33.1.1
  - dependency-name: datastore-level
    versions:
    - 3.0.0
    - 4.0.0
    - 5.0.0
  - dependency-name: interface-datastore
    versions:
    - 3.0.3
    - 3.0.4
    - 3.0.5
  - dependency-name: ipfs-utils
    versions:
    - 6.0.0
    - 6.0.1
    - 6.0.3
    - 6.0.4
    - 6.0.5
    - 6.0.6
  - dependency-name: datastore-core
    versions:
    - 3.0.0
